
file(STRINGS "${PMAKE_VERSION_FILE}" PMAKE_VERSION_PARTS REGEX "#define ${PMAKE_VERSION_ID}_VERSION_[A-Z]+[ ]+" )

string(REGEX REPLACE ".+${PMAKE_VERSION_ID}_VERSION_MAJOR[ ]+([0-9]+).*" "\\1" PMAKE_VERSION_MAJOR "${PMAKE_VERSION_PARTS}")
string(REGEX REPLACE ".+${PMAKE_VERSION_ID}_VERSION_MINOR[ ]+([0-9]+).*" "\\1" PMAKE_VERSION_MINOR "${PMAKE_VERSION_PARTS}")
string(REGEX REPLACE ".+${PMAKE_VERSION_ID}_VERSION_REVISION[ ]+([0-9]+).*" "\\1" PMAKE_VERSION_PATCH "${PMAKE_VERSION_PARTS}")
string(REGEX REPLACE ".+${PMAKE_VERSION_ID}_VERSION_STATUS[ ]+\"([^\"]*)\".*" "\\1" PMAKE_VERSION_STATUS "${PMAKE_VERSION_PARTS}")

set(PMAKE_VERSION_PLAIN "${PMAKE_VERSION_MAJOR}.${PMAKE_VERSION_MINOR}.${PMAKE_VERSION_PATCH}")
set(PMAKE_VERSION "${PMAKE_VERSION_PLAIN}${PMAKE_VERSION_STATUS}")
set(PMAKE_SOVERSION "${PMAKE_VERSION_MAJOR}.${PMAKE_VERSION_MINOR}")
set(PMAKE_LIBVERSION "${PMAKE_VERSION_MAJOR}.${PMAKE_VERSION_MINOR}.${PMAKE_VERSION_PATCH}")

# create a dependency on the version file
# we never use the output of the following command but cmake will rerun automatically if the version file changes
configure_file("${PMAKE_VERSION_FILE}" "${CMAKE_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/_junk/version.junk" COPYONLY)
